### ISSUE TITLE
貌似现在最新版思源不可以用这个插件了

### ISSUE THREAD

**Issue by Chenm4** [zuoez02/siyuan-plugin-docky#8]
![Clip_2024-03-12_10-07-56](https://github.com/zuoez02/siyuan-plugin-docky/assets/98648589/dbe899fb-611b-42ce-b223-29c2548807a5)

**Comment by zuoez02** [comment]
更新了吗？我这没有这个问题，思源3.0.2
________________________________
发件人: 朝生暮 ***@***.***>
发送时间: 2024年3月12日 10:08
收件人: zuoez02/siyuan-plugin-docky ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zuoez02/siyuan-plugin-docky] 貌似现在最新版思源不可以用这个插件了 (Issue #8)


Clip_2024-03-12_10-07-56.png (view on web)<https://github.com/zuoez02/siyuan-plugin-docky/assets/98648589/dbe899fb-611b-42ce-b223-29c2548807a5>

―

**Comment by nuomici2222** [comment]
是不是界面没显示全，把侧栏拉大能看到加号，感觉排版好像错位了，思源v3.0.7。

![image](https://github.com/zuoez02/siyuan-plugin-docky/assets/94222529/4a29022d-0a56-45c6-80b8-e0dc0467444a)

**Comment by zuoez02** [comment]
加个代码片段修正一下
```css
.block__logo svg {
    margin-right: 4px;
    height: 16px;
    width: 16px;
    padding: 4px;
    flex-shrink: 0;
}
```
